import { db } from './db';
import { employers, jobs } from '@shared/schema';

async function seed() {
  console.log('Seeding database...');

  // Create employers
  const employerData = [
    {
      name: 'GulfTalent Partners',
      logo: '/logos/gulftalent.svg',
      about: 'Leading recruitment agency specializing in Gulf region placements.',
      website: 'https://example.com',
      whatsappNumber: '971501234567',
      email: 'hr@gulftalentpartners.com',
    },
    {
      name: 'CarePlus KSA',
      logo: '/logos/careplus.svg',
      about: 'Premier healthcare provider in Saudi Arabia with state-of-the-art facilities.',
      website: 'https://example.com',
      whatsappNumber: '966501112223',
      email: 'apply@careplus-ksa.com',
    },
    {
      name: 'QBuild Partners',
      logo: '/logos/qbuild.svg',
      about: 'Major construction and infrastructure development company in Qatar.',
      website: 'https://example.com',
      whatsappNumber: '97455566778',
      email: 'talent@qbuild.qa',
    },
    {
      name: 'Tech Solutions UAE',
      logo: '/logos/techsolutions.svg',
      about: 'Innovative IT solutions and software development company based in Dubai.',
      website: 'https://example.com',
      whatsappNumber: '971505554444',
      email: 'jobs@techsolutions.ae',
    },
  ];

  const createdEmployers = await db.insert(employers).values(employerData).returning();
  console.log(`Created ${createdEmployers.length} employers`);

  // Create jobs
  const jobsData = [
    {
      slug: 'business-development-manager-dubai',
      titleEn: 'Business Development Manager',
      titleAr: 'مدير تطوير الأعمال',
      descriptionEn: 'Drive partnerships and revenue across GCC markets. Lead strategic initiatives to expand our client base and develop new business opportunities in the region.',
      descriptionAr: 'قيادة الشراكات والإيرادات عبر أسواق الخليج. قيادة المبادرات الاستراتيجية لتوسيع قاعدة عملائنا وتطوير فرص عمل جديدة في المنطقة.',
      responsibilitiesEn: '• Develop and execute business development strategies\n• Build and maintain relationships with key clients\n• Identify new market opportunities\n• Negotiate contracts and close deals\n• Collaborate with cross-functional teams',
      responsibilitiesAr: '• تطوير وتنفيذ استراتيجيات تطوير الأعمال\n• بناء والحفاظ على العلاقات مع العملاء الرئيسيين\n• تحديد فرص السوق الجديدة\n• التفاوض على العقود وإتمام الصفقات\n• التعاون مع الفرق متعددة الوظائف',
      requirementsEn: '• 5+ years of experience in business development\n• Strong negotiation and communication skills\n• Experience in GCC markets preferred\n• Bachelor\'s degree in Business or related field\n• Fluent in English, Arabic is a plus',
      requirementsAr: '• خبرة 5 سنوات في تطوير الأعمال\n• مهارات قوية في التفاوض والتواصل\n• الخبرة في أسواق الخليج مفضلة\n• درجة البكالوريوس في إدارة الأعمال أو مجال ذي صلة\n• إجادة اللغة الإنجليزية، العربية ميزة إضافية',
      country: 'UAE',
      city: 'Dubai',
      category: 'Sales',
      contractType: 'Full-time',
      experienceLevel: '5-7',
      salaryMin: 18000,
      salaryMax: 23000,
      currency: 'AED',
      benefits: ['Housing allowance', 'Medical insurance', 'Annual flight tickets', 'Performance bonus'],
      visaSponsorship: true,
      relocation: true,
      housing: true,
      remote: false,
      urgent: false,
      expiresAt: new Date('2025-11-15'),
      status: 'published',
      featured: true,
      employerId: createdEmployers[0].id,
    },
    {
      slug: 'registered-nurse-riyadh',
      titleEn: 'Registered Nurse',
      titleAr: 'ممرضة مسجلة',
      descriptionEn: 'Hospital-based role with accommodation. Provide high-quality patient care in a modern medical facility.',
      descriptionAr: 'دور في مستشفى مع سكن. تقديم رعاية عالية الجودة للمرضى في منشأة طبية حديثة.',
      responsibilitiesEn: '• Provide direct patient care and monitoring\n• Administer medications and treatments\n• Maintain accurate patient records\n• Collaborate with medical team\n• Ensure patient safety and comfort',
      responsibilitiesAr: '• تقديم رعاية مباشرة ومراقبة للمرضى\n• إعطاء الأدوية والعلاجات\n• الحفاظ على سجلات دقيقة للمرضى\n• التعاون مع الفريق الطبي\n• ضمان سلامة وراحة المرضى',
      requirementsEn: '• Valid nursing license\n• 2-4 years of experience\n• BLS and ACLS certification\n• Good English communication skills\n• Experience in acute care preferred',
      requirementsAr: '• رخصة تمريض سارية المفعول\n• خبرة 2-4 سنوات\n• شهادة BLS و ACLS\n• مهارات تواصل جيدة باللغة الإنجليزية\n• الخبرة في الرعاية الحادة مفضلة',
      country: 'KSA',
      city: 'Riyadh',
      category: 'Healthcare',
      contractType: 'Full-time',
      experienceLevel: '2-4',
      salaryMin: 9000,
      salaryMax: 12000,
      currency: 'SAR',
      benefits: ['Housing', 'Visa sponsorship', 'Annual flight', 'Medical insurance'],
      visaSponsorship: true,
      relocation: true,
      housing: true,
      remote: false,
      urgent: true,
      expiresAt: new Date('2025-11-01'),
      status: 'published',
      featured: false,
      employerId: createdEmployers[1].id,
    },
    {
      slug: 'site-engineer-doha',
      titleEn: 'Site Engineer',
      titleAr: 'مهندس موقع',
      descriptionEn: 'Large infrastructure project in Doha. Oversee construction activities and ensure project quality standards.',
      descriptionAr: 'مشروع بنية تحتية كبير في الدوحة. الإشراف على أنشطة البناء وضمان معايير جودة المشروع.',
      responsibilitiesEn: '• Supervise construction activities on site\n• Ensure compliance with safety regulations\n• Coordinate with contractors and suppliers\n• Monitor project progress and quality\n• Prepare progress reports',
      responsibilitiesAr: '• الإشراف على أنشطة البناء في الموقع\n• ضمان الامتثال للوائح السلامة\n• التنسيق مع المقاولين والموردين\n• مراقبة تقدم المشروع والجودة\n• إعداد تقارير التقدم',
      requirementsEn: '• Bachelor\'s degree in Civil Engineering\n• 5-7 years of site experience\n• Knowledge of construction methods\n• Strong leadership skills\n• Proficient in AutoCAD and MS Project',
      requirementsAr: '• درجة البكالوريوس في الهندسة المدنية\n• خبرة 5-7 سنوات في الموقع\n• معرفة بطرق البناء\n• مهارات قيادية قوية\n• إتقان AutoCAD و MS Project',
      country: 'QAT',
      city: 'Doha',
      category: 'Construction',
      contractType: 'Contract',
      experienceLevel: '5-7',
      salaryMin: 14000,
      salaryMax: 18000,
      currency: 'QAR',
      benefits: ['Transport', 'Medical insurance', 'End of service benefits'],
      visaSponsorship: true,
      relocation: true,
      housing: false,
      remote: false,
      urgent: false,
      expiresAt: new Date('2025-12-01'),
      status: 'published',
      featured: false,
      employerId: createdEmployers[2].id,
    },
    {
      slug: 'senior-software-engineer-dubai',
      titleEn: 'Senior Software Engineer',
      titleAr: 'مهندس برمجيات أقدم',
      descriptionEn: 'Join our innovative tech team to build cutting-edge software solutions for the Middle East market.',
      descriptionAr: 'انضم إلى فريقنا التقني المبتكر لبناء حلول برمجية متطورة لسوق الشرق الأوسط.',
      responsibilitiesEn: '• Design and develop scalable software solutions\n• Lead technical architecture decisions\n• Mentor junior developers\n• Collaborate with product team\n• Ensure code quality and best practices',
      responsibilitiesAr: '• تصميم وتطوير حلول برمجية قابلة للتوسع\n• قيادة قرارات الهندسة المعمارية التقنية\n• توجيه المطورين المبتدئين\n• التعاون مع فريق المنتج\n• ضمان جودة الكود وأفضل الممارسات',
      requirementsEn: '• 5+ years of software development experience\n• Proficient in React, Node.js, and TypeScript\n• Experience with cloud platforms (AWS/Azure)\n• Strong problem-solving skills\n• Bachelor\'s degree in Computer Science',
      requirementsAr: '• خبرة 5 سنوات في تطوير البرمجيات\n• إتقان React و Node.js و TypeScript\n• الخبرة في منصات السحابة (AWS/Azure)\n• مهارات قوية في حل المشكلات\n• درجة البكالوريوس في علوم الحاسوب',
      country: 'UAE',
      city: 'Dubai',
      category: 'IT',
      contractType: 'Full-time',
      experienceLevel: '5-7',
      salaryMin: 20000,
      salaryMax: 28000,
      currency: 'AED',
      benefits: ['Health insurance', 'Flexible working hours', 'Learning budget', 'Stock options'],
      visaSponsorship: true,
      relocation: true,
      housing: false,
      remote: true,
      urgent: false,
      expiresAt: new Date('2025-12-15'),
      status: 'published',
      featured: true,
      employerId: createdEmployers[3].id,
    },
    {
      slug: 'accountant-jeddah',
      titleEn: 'Senior Accountant',
      titleAr: 'محاسب أقدم',
      descriptionEn: 'Manage financial operations for a growing company in Jeddah with opportunities for career advancement.',
      descriptionAr: 'إدارة العمليات المالية لشركة متنامية في جدة مع فرص للتقدم الوظيفي.',
      responsibilitiesEn: '• Prepare financial statements and reports\n• Manage accounts payable and receivable\n• Ensure compliance with local regulations\n• Coordinate with external auditors\n• Assist in budget preparation',
      responsibilitiesAr: '• إعداد البيانات والتقارير المالية\n• إدارة الحسابات الدائنة والمدينة\n• ضمان الامتثال للوائح المحلية\n• التنسيق مع المدققين الخارجيين\n• المساعدة في إعداد الميزانية',
      requirementsEn: '• Bachelor\'s degree in Accounting or Finance\n• 3-5 years of accounting experience\n• Knowledge of Saudi GAAP\n• Proficient in accounting software\n• CPA or SOCPA certification preferred',
      requirementsAr: '• درجة البكالوريوس في المحاسبة أو المالية\n• خبرة 3-5 سنوات في المحاسبة\n• معرفة بمعايير المحاسبة السعودية\n• إتقان برامج المحاسبة\n• شهادة CPA أو SOCPA مفضلة',
      country: 'KSA',
      city: 'Jeddah',
      category: 'Finance',
      contractType: 'Full-time',
      experienceLevel: '2-4',
      salaryMin: 10000,
      salaryMax: 14000,
      currency: 'SAR',
      benefits: ['Medical insurance', 'Annual bonus', 'Transportation allowance'],
      visaSponsorship: true,
      relocation: false,
      housing: false,
      remote: false,
      urgent: false,
      expiresAt: new Date('2025-11-30'),
      status: 'published',
      featured: false,
      employerId: createdEmployers[0].id,
    },
    {
      slug: 'hotel-manager-abu-dhabi',
      titleEn: 'Hotel Operations Manager',
      titleAr: 'مدير عمليات الفندق',
      descriptionEn: 'Lead operations for a luxury hotel in Abu Dhabi, ensuring exceptional guest experiences.',
      descriptionAr: 'قيادة العمليات لفندق فاخر في أبوظبي، وضمان تجارب استثنائية للنزلاء.',
      responsibilitiesEn: '• Oversee daily hotel operations\n• Manage staff and ensure high service standards\n• Monitor financial performance\n• Implement quality control measures\n• Handle guest relations and feedback',
      responsibilitiesAr: '• الإشراف على العمليات اليومية للفندق\n• إدارة الموظفين وضمان معايير خدمة عالية\n• مراقبة الأداء المالي\n• تنفيذ تدابير مراقبة الجودة\n• التعامل مع علاقات النزلاء والملاحظات',
      requirementsEn: '• 8+ years of hospitality experience\n• Bachelor\'s degree in Hospitality Management\n• Strong leadership and communication skills\n• Experience with luxury hotel operations\n• Fluent in English and Arabic',
      requirementsAr: '• خبرة 8 سنوات في قطاع الضيافة\n• درجة البكالوريوس في إدارة الضيافة\n• مهارات قيادية وتواصل قوية\n• الخبرة في عمليات الفنادق الفاخرة\n• إجادة اللغة الإنجليزية والعربية',
      country: 'UAE',
      city: 'Abu Dhabi',
      category: 'Hospitality',
      contractType: 'Full-time',
      experienceLevel: '8+',
      salaryMin: 22000,
      salaryMax: 30000,
      currency: 'AED',
      benefits: ['Accommodation', 'Medical insurance', 'Performance bonuses', 'Meals'],
      visaSponsorship: true,
      relocation: true,
      housing: true,
      remote: false,
      urgent: true,
      expiresAt: new Date('2025-10-31'),
      status: 'published',
      featured: true,
      employerId: createdEmployers[3].id,
    },
  ];

  const createdJobs = await db.insert(jobs).values(jobsData).returning();
  console.log(`Created ${createdJobs.length} jobs`);

  console.log('Seeding completed successfully!');
}

seed()
  .catch((error) => {
    console.error('Seeding failed:', error);
    process.exit(1);
  })
  .finally(() => {
    process.exit(0);
  });
